### PR TITLE
Propagate user signal to memory and back

### PR DESCRIPTION
**Pull request by JeanRochCoulon**
The user fields were missing in AXI bus. This PR adds the user field support.

Signed-off-by: Jean-Roch Coulon <jean-roch.coulon@thalesgroup.com>

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@zarubaf Could you have a look to this PR? Or transmit it to repository owner. Thanks

**Comment by zarubaf** [comment]
@accuminium I forgot who owns this since I left. Can you please CC the right person? Thanks

**Review by andreaskurth — APPROVED** [review]
LGTM, thanks!

**Comment by JeanRochCoulon** [comment]
Thanks @accuminium and @zarubaf , it allows me to add user bits on cva6 busses !   Have a good day

**Pull request merged**
